#!/bin/sh
	if [ -f /run/.containerenv ]; then
                    exec flatpak-spawn --host toolbox run -c "arch" /usr/sbin/git "$@"
                elif [ -z "$container" ] ; then
                    exec /usr/bin/toolbox run -c arch git "$@"
                else
                    exec host-spawn toolbox run -c arch /usr/sbin/git "$@"
                fi
            